### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Clark131411414** [GMod4Life/noah_hud_fivem#1]
[noah_hud_fivem-main] addons/noah_hud_fivem-main/lua/autorun/cl_hud.lua:37: bad argument #1 to 'ceil' (number expected, got nil)
  
ceil - [C]:-1
fn - addons/noah_hud_fivem-main/lua/autorun/cl_hud.lua:37
unknown - addons/ulib/lua/ulib/shared/hook.lua:109

It doesn't work on the server at all, it just causes Lua problems all the time

**Comment by noahballas** [comment]
> [noah_hud_fivem-main] addons/noah_hud_fivem-main/lua/autorun/cl_hud.lua:37: bad argument #1 to 'ceil' (number expected, got nil)
> 
> ceil - [C]:-1 fn - addons/noah_hud_fivem-main/lua/autorun/cl_hud.lua:37 unknown - addons/ulib/lua/ulib/shared/hook.lua:109
> 
> It doesn't work on the server at all, it just causes Lua problems all the time

Hello, I'll check it during the day :'(

Sorry

**Comment by Clark131411414** [comment]
Can you let me know via discord dm?

FA: .clark31

**Comment by noahballas** [comment]
Yes
